delete from sys_akses_menu;
DELETE FROM MENU;
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (1,0,'ROOT',NULL,0,1,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (2,1,'ADMIN',NULL,1,1,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (3,2,'Audit Trail',NULL,2,1,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (4,2,'Log Email',NULL,2,2,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (5,2,'Log SMS',NULL,2,3,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (6,1,'MASTER',NULL,1,2,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (7,6,'Divisi','master/divisi',2,1,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (8,6,'Group User','master/groupuser',2,2,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (9,6,'Sub Divisi','master/subdivisi',2,3,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (10,6,'Departmen','master/departmen',2,4,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (11,6,'Lokasi','master/lokasi',2,5,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (12,6,'Menu','master/menu',2,6,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (13,6,'Fungsi User','master/mfungsi',2,7,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (14,6,'Group User','master/groupuser',2,8,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (15,6,'User','master/user',2,9,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (16,6,'User Divisi','master/userdivisi',2,10,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (17,6,'Group Biaya','master/groupbiaya',2,11,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (18,6,'Detail Biaya','master/detailbiaya',2,12,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (19,6,'Hak Biaya','master/hakbiaya',2,13,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (20,6,'Hak Approve','master/hakapprove',2,14,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (21,1,'Transaksi',NULL,1,3,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (22,21,'Entry PPUC',NULL,2,1,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (23,21,'Confirm PPUC',NULL,2,2,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (24,21,'Approval Divisi',NULL,2,3,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (25,21,'Realisasi PPUC untuk Cabang',NULL,2,4,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (26,21,'Batal PPUC',NULL,2,5,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (27,21,'Confirm Realisasi PPUC untuk Cabang',NULL,2,6,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (28,21,'Entry PPUCVerifikasi Realisasi PPUC oleh OC',NULL,2,7,1,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `menu` (`sys_menu_id`,`parent`,`nama`,`link`,`level`,`urut`,`f_aktif`,`sys_user_create`,`sys_tgl_create`,`sys_jam_create`,`sys_user_nonaktif`,`sys_tgl_nonaktif`,`sys_jam_nonaktif`) VALUES (29,21,'Transfer Finance',NULL,2,8,1,NULL,NULL,NULL,NULL,NULL,NULL);




insert into sys_akses_menu
SELECT 'ADMIN',sys_menu_id, 'SYSTEM', sysdate() from menu;